#This File's name is ui_read.py
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Zheng/Desktop/AI/reader/read.ui',
# licensing of 'C:/Users/Zheng/Desktop/AI/reader/read.ui' applies.
#
# Created: Sat Nov 30 19:28:13 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("read.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 251, 101))
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 120, 704, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choser = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(22)
        self.choser.setFont(font)
        self.choser.setObjectName("choser")
        self.choser.addItem("")
        self.choser.addItem("")
        self.choser.addItem("")
        self.choser.addItem("")
        self.choser.addItem("")
        self.choser.addItem("")
        self.choser.addItem("")
        self.horizontalLayout.addWidget(self.choser)
        self.open = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(22)
        self.open.setFont(font)
        self.open.setObjectName("open")
        self.horizontalLayout.addWidget(self.open)
        self.create = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(22)
        self.create.setFont(font)
        self.create.setObjectName("create")
        self.horizontalLayout.addWidget(self.create)
        self.play = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("等线 Light")
        font.setPointSize(22)
        self.play.setFont(font)
        self.play.setObjectName("play")
        self.horizontalLayout.addWidget(self.play)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionweb = QtWidgets.QAction(MainWindow)
        self.actionweb.setObjectName("actionweb")
        self.menu.addAction(self.actionOpen)
        self.menu_2.addAction(self.actionweb)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "小度说书", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "小度说书", None, -1))
        self.textEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "请键入……", None, -1))
        self.choser.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "度逍遥", None, -1))
        self.choser.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "度博文", None, -1))
        self.choser.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "度小童", None, -1))
        self.choser.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "度丫丫", None, -1))
        self.choser.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "度小美", None, -1))
        self.choser.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "度小宇", None, -1))
        self.choser.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "度小萌", None, -1))
        self.open.setText(QtWidgets.QApplication.translate("MainWindow", "导入文本文件", None, -1))
        self.create.setText(QtWidgets.QApplication.translate("MainWindow", "生成语音", None, -1))
        self.play.setText(QtWidgets.QApplication.translate("MainWindow", "播放生成的语音", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "文件", None, -1))
        self.menu_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "关于", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "打开", None, -1))
        self.actionweb.setText(QtWidgets.QApplication.translate("MainWindow", "作者网站", None, -1))

